In [1]:
import numpy as np

In [2]:
a = np.array([[3, -2, 3], [-3, 0, -1], [-1, -3, 2]])
b = np.array([[1, 0, 4], [2, 2, 3], [2, -1, -1]])
print(5*(a + b))

[[ 20 -10  35]
 [ -5  10  10]
 [  5 -20   5]]


In [6]:
def f(p, l, t):
    return -2*p + 3*l + 2*t


for i in range(1, 4):
    for j in range(1, 4):
        print(f(i, j, 3), end=" ")
    print()

7 10 13 
5 8 11 
3 6 9 
