In [1]:
import numpy as np
import numpy.linalg as nl
from numpy.typing import NDArray
import scipy.linalg as sp
from sympy import Matrix

In [13]:
def to_string(a):
	result = ""
	for i in range(len(a)):
		for j in range(len(a[i])):
			if j != len(a) - 1:
				result += str(a[i][j]) + ", "
			else:
				result += str(a[i][j]) + "; "
	return "[" + result[:-2] + "]"

In [15]:
A = np.array([[1, 0, 1, -3], [0, 1, 1, -1], [-1, 1, 1, 0], [-2, -2, -4, 9]])
QR = nl.qr(A)
to_string(QR[1])

'[-2.449489742783178, -1.2247448713915892, -3.265986323710904, 8.573214099741126; 0.0, -2.1213203435596424, -2.8284271247461907, 4.006938426723769; 0.0, 0.0, -0.5773502691896252, 1.1547005383792517; 0.0, 0.0, 0.0, 0.3333333333333322]'

In [40]:
A = np.array([[6, 6, -8], [-9, -15, 21], [-12, -16, 37]])
L = np.array([[1, 0, 0], [-1.5, 1, 0], [-2, 2/3, 1]])
U = [[6, 6, -8], [0, -6, 9], [0, 0, 15]]
R = sp.lu(A) # Use wolfram

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.        ,  1.        ,  0.75      ],
       [ 1.        ,  0.66666667, -0.5       ]])

In [51]:
np.printoptions(precision=0, suppress=True)
A = np.array([[3, 3, -3], [3, 6, -6]])
sp.svd(A)[1] # Use wolfram

array([10.31884524,  1.2334638 ])

In [56]:
A = np.array([[1, 0], [-1, 1]])
G = np.array([[5, 7], [7, 10]])
nl.inv(G) @ A.transpose() @ G

array([[ -69., -100.],
       [  49.,   71.]])