In [ ]:
import numpy as np

In [ ]:
main_v = np.array([[-2, 3, 7, -7, -20], [1, -1, -3, 4, 8], [0, 0, 1, -1, -2]])

In [ ]:
main_v

In [ ]:
v1 = main_v.dot(np.array([[-2], [-2], [1], [-14], [1]]))
v2 = main_v.dot(np.array([[1], [1], [0], [6], [-1]]))
v3 = main_v.dot(np.array([[1], [0], [0], [3], [2]]))

In [ ]:
v1, v2, v3

In [ ]:
main_v.dot(np.array([[-2, 1, 1], [-2, 1, 0], [1, 0, 0], [-14, 6, 3], [1, -1, 2]]))

In [2]:
main_v = np.array([[-2, 3, 7, -7, -20], [1, -1, -3, 4, 8], [0, 0, 1, -1, -2]])

In [3]:
main_v

array([[ -2,   3,   7,  -7, -20],
       [  1,  -1,  -3,   4,   8],
       [  0,   0,   1,  -1,  -2]])

In [8]:
v1 = main_v.dot(np.array([[-2], [-2], [1], [-14], [1]]))
v2 = main_v.dot(np.array([[1], [1], [0], [6], [-1]]))
v3 = main_v.dot(np.array([[1], [0], [0], [3], [2]]))

In [9]:
v1, v2, v3

(array([[ 83],
        [-51],
        [ 13]]),
 array([[-21],
        [ 16],
        [ -4]]),
 array([[-63],
        [ 29],
        [ -7]]))

In [10]:
main_v.dot(np.array([[-2, 1, 1], [-2, 1, 0], [1, 0, 0], [-14, 6, 3], [1, -1, 2]]))

array([[ 83, -21, -63],
       [-51,  16,  29],
       [ 13,  -4,  -7]])